---

vIOS1:
    hostname: "192.168.1.101"
    groups:
        - north
vIOS2:
    hostname: "192.168.1.102"
    groups:
        - north
vIOS3:
    hostname: "192.168.1.103"
    groups:
        - north
vIOS4:
    hostname: "192.168.1.104"
    groups:
        - north
vIOS5:
    hostname: "192.168.1.105"
    groups:
        - south
vIOS6:
    hostname: "192.168.1.106"
    groups:
        - south
vIOS7:
    hostname: "192.168.1.107"
    groups:
        - south
vIOS8:
    hostname: "192.168.1.108"
    groups:
        - south
